select SUM (F.VL_PAGO) AS VALOR_TOTAL
      ,FP.NM_FORMA_PAGAMENTO
   
   FROM FATURA F , FORMA_PAGAMENTO FP
   WHERE F.ID_FORMA_PAGAMENTO = FP.ID_FORMA_PAGAMENTO
   AND F.DT_PAGO >= '01/10/2015'
   AND F.DT_PAGO < '01/11/2015'
   
   GROUP BY FP.NM_FORMA_PAGAMENTO
     