select P.ID_PRODUTO
      ,P.NM_PRODUTO
      ,PL.ID_PRODUTO_LOCAL
      ,PL.QT_ATUAL
      ,PL.VL_VENDA
      ,PL.VL_COMPRA
      ,L.NM_LOCAL
      ,F.NM_FILIAL
      ,U.NM_LOGIN
      ,U.ID_USUARIO
      
   FROM PRODUTO P , PRODUTO_LOCAL PL, LOCAL L , FILIAL F , USUARIO U
    WHERE P.ID_PRODUTO = PL.ID_PRODUTO
    AND   PL.ID_LOCAL = L.ID_LOCAL
    AND   L.ID_FILIAL = F.ID_FILIAL
    AND   U.ID_FILIAL = F.ID_FILIAL